# Generated by Django 3.2.4 on 2021-08-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Pet Type',
                'verbose_name_plural': 'Pet Types',
                'ordering': ['id'],
            },
        ),
    ]
