# Generated by Django 3.2.4 on 2021-08-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210805_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='pet_photo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
