# Generated by Django 3.2.5 on 2021-10-01 02:31

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profileclient_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(max_length=1024, upload_to=utils.functions.upload_to_path),
        ),
    ]
