# Generated by Django 3.2.5 on 2021-08-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
