# Exemplo completo de docker compose https://gist.github.com/ju2wheels/1885539d63dbcfb20729

# Versão do Docker Compose
version: '3'

# Serviços que este compose cria, neste caso um container para o banco e um para a WEB
services:
    db:
        image: postgres # Nome da imagem baseada na imagem padrão do postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
          - postgres-pgadmin-network

    web:
        build: . # o ponto indica que este serviço será baseado no dockerfile que esta no diretorio corrente
        volumes:
            - .:/usr/src/app # O Diretorio onde esta a aplicação
        ports:
            - "8000:8000" # a porta 8000 do container mapeia para o porta 8000 da maquina local (rodando o container)
        depends_on:
            - db
        networks:
          - postgres-pgadmin-network
        environment: # foi criada uma migrations no app "users" que le essas variaveis de ambinete e cria o superuser para o Django
            DJANGO_DB_NAME: "db"
            DJANGO_SU_NAME: "admin"
            DJANGO_SU_EMAIL: "admin@example.com"
            DJANGO_SU_PASSWORD: "1234"

    pgadmin:
        image: dpage/pgadmin4
        environment:
            #PGADMIN_LISTEN_ADDRESS: 0.0.0.0
            #PGADMIN_LISTEN_PORT: 8080
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - db
        networks:
          - postgres-pgadmin-network
        #tty: true
    
networks: 
    postgres-pgadmin-network:
        driver: bridge

