# Generated by Django 3.2.4 on 2021-08-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pet_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_photo',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
