# Generated by Django 3.2.4 on 2021-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210806_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decision',
            field=models.TextField(default=''),
        ),
    ]
