# Generated by Django 3.2.4 on 2021-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
