# Generated by Django 3.2.5 on 2021-10-01 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_photo'),
        ('booking', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='profile_client_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile_client_author', to='user.profileclient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='profile_server_reviewed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile_server_reviewed', to='user.profileserver'),
            preserve_default=False,
        ),
    ]
